export const TYPES = [
  {"id":"password","label":"Login","plural":"Logins","icon":"globe","titleKey":"account","primary":"password","fields":[{"key":"account","label":"Name","kind":"text"},{"key":"username","label":"Username","kind":"text","icon":"user"},{"key":"password","label":"Password","kind":"password","icon":"key-round"},{"key":"website","label":"Website","kind":"url","icon":"globe"},{"key":"urls","label":"Other websites","kind":"list","icon":"link-2"}]},
  {"id":"totp","label":"Authenticator","plural":"Authenticator","icon":"timer","titleKey":"account","primary":"secret","fields":[{"key":"account","label":"Name","kind":"text"},{"key":"secret","label":"Setup key","kind":"totp","icon":"timer"},{"key":"domain","label":"Website","kind":"url","icon":"globe"}]},
  {"id":"note","label":"Secure note","plural":"Secure notes","icon":"sticky-note","titleKey":"name","primary":"content","fields":[{"key":"name","label":"Title","kind":"text"},{"key":"content","label":"Note","kind":"note","icon":"file-text"}]},
  {"id":"wifi","label":"Wi-Fi network","plural":"Wi-Fi","icon":"wifi","titleKey":"ssid","primary":"password","fields":[{"key":"ssid","label":"Network name","kind":"text"},{"key":"password","label":"Password","kind":"password","icon":"key-round"},{"key":"security_type","label":"Security","kind":"select","icon":"shield-check"},{"key":"router_ip","label":"Router address","kind":"text","mono":true,"icon":"server"}]},
  {"id":"govid","label":"Government ID","plural":"Identities","icon":"id-card","titleKey":"name","primary":"id_number","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"type","label":"Document","kind":"select","icon":"id-card"},{"key":"id_number","label":"ID number","kind":"secret","mono":true,"icon":"hash"},{"key":"expiry","label":"Expires","kind":"date","icon":"calendar"}]},
  {"id":"medical","label":"Medical record","plural":"Medical","icon":"heart-pulse","titleKey":"label","primary":"insurance_id","fields":[{"key":"label","label":"Name","kind":"text"},{"key":"insurance_id","label":"Insurance ID","kind":"text","mono":true,"icon":"hash"},{"key":"prescriptions","label":"Prescriptions","kind":"multiline","icon":"pill"},{"key":"allergies","label":"Allergies","kind":"text","icon":"circle-alert"}]},
  {"id":"travel","label":"Travel","plural":"Travel","icon":"plane","titleKey":"label","primary":"booking_code","fields":[{"key":"label","label":"Name","kind":"text"},{"key":"ticket_number","label":"Ticket number","kind":"text","mono":true,"icon":"ticket"},{"key":"booking_code","label":"Booking code","kind":"secret","mono":true,"icon":"hash"},{"key":"loyalty_program","label":"Loyalty program","kind":"text","icon":"award"}]},
  {"id":"contact","label":"Contact","plural":"Contacts","icon":"contact","titleKey":"name","primary":"phone","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"phone","label":"Phone","kind":"phone","mono":true,"icon":"phone"},{"key":"email","label":"Email","kind":"email","icon":"at-sign"},{"key":"address","label":"Address","kind":"multiline","icon":"map-pin"},{"key":"emergency","label":"Emergency contact","kind":"bool","icon":"life-buoy"}]},
  {"id":"recovery","label":"Recovery codes","plural":"Recovery codes","icon":"life-buoy","titleKey":"service","primary":"codes","fields":[{"key":"service","label":"Service","kind":"text"},{"key":"codes","label":"Codes","kind":"codes","icon":"list"}]},
  {"id":"apikey","label":"API key","plural":"API keys","icon":"key-round","titleKey":"name","primary":"key","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"service","label":"Service","kind":"text","icon":"server"},{"key":"key","label":"Key","kind":"secret","mono":true,"icon":"key-round"}]},
  {"id":"token","label":"Token","plural":"Tokens","icon":"ticket","titleKey":"name","primary":"token","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"token","label":"Token","kind":"secret","mono":true,"icon":"key-round"},{"key":"type","label":"Kind","kind":"text","icon":"tag"}]},
  {"id":"ssh_key","label":"SSH key","plural":"SSH keys","icon":"key-square","titleKey":"name","primary":"private_key","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"private_key","label":"Private key","kind":"secretBlock","icon":"key-round"}]},
  {"id":"ssh_config","label":"SSH host","plural":"SSH hosts","icon":"server","titleKey":"alias","primary":"private_key","fields":[{"key":"alias","label":"Alias","kind":"text","mono":true},{"key":"host","label":"Host","kind":"text","mono":true,"icon":"server"},{"key":"user","label":"User","kind":"text","mono":true,"icon":"user"},{"key":"port","label":"Port","kind":"number","mono":true,"icon":"hash"},{"key":"key_path","label":"Key path","kind":"text","mono":true,"icon":"file-key"},{"key":"private_key","label":"Private key","kind":"secretBlock","icon":"key-round"},{"key":"fingerprint","label":"Fingerprint","kind":"text","mono":true,"icon":"fingerprint"}]},
  {"id":"cloud","label":"Cloud credentials","plural":"Cloud credentials","icon":"cloud","titleKey":"label","primary":"secret_key","fields":[{"key":"label","label":"Name","kind":"text"},{"key":"access_key","label":"Access key","kind":"secret","mono":true,"icon":"key"},{"key":"secret_key","label":"Secret key","kind":"secret","mono":true,"icon":"key-round"},{"key":"region","label":"Region","kind":"text","mono":true,"icon":"map-pin"},{"key":"account_id","label":"Account ID","kind":"text","mono":true,"icon":"hash"},{"key":"role","label":"Role","kind":"text","icon":"user"},{"key":"expiration","label":"Expires","kind":"date","icon":"calendar"}]},
  {"id":"k8s","label":"Kubernetes","plural":"Kubernetes","icon":"ship-wheel","titleKey":"name","primary":"cluster_url","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"cluster_url","label":"Cluster URL","kind":"text","mono":true,"icon":"globe"},{"key":"namespace","label":"Namespace","kind":"text","mono":true,"icon":"layers"},{"key":"expiration","label":"Expires","kind":"date","icon":"calendar"}]},
  {"id":"docker","label":"Docker registry","plural":"Docker registries","icon":"container","titleKey":"name","primary":"token","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"registry_url","label":"Registry","kind":"text","mono":true,"icon":"globe"},{"key":"username","label":"Username","kind":"text","icon":"user"},{"key":"token","label":"Token","kind":"secret","mono":true,"icon":"key-round"}]},
  {"id":"cicd","label":"CI/CD secret","plural":"CI/CD secrets","icon":"workflow","titleKey":"name","primary":"webhook","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"webhook","label":"Webhook","kind":"secret","mono":true,"icon":"webhook"},{"key":"env_vars","label":"Environment variables","kind":"env","icon":"terminal"}]},
  {"id":"certificate","label":"Certificate","plural":"Certificates","icon":"file-key","titleKey":"label","primary":"private_key","fields":[{"key":"label","label":"Name","kind":"text"},{"key":"issuer","label":"Issuer","kind":"text","icon":"badge-check"},{"key":"expiry","label":"Expires","kind":"date","icon":"calendar"},{"key":"cert_data","label":"Certificate","kind":"secretBlock","icon":"file-text"},{"key":"private_key","label":"Private key","kind":"secretBlock","icon":"key-round"}]},
  {"id":"banking","label":"Card or account","plural":"Banking","icon":"credit-card","titleKey":"label","primary":"details","fields":[{"key":"label","label":"Name","kind":"text"},{"key":"type","label":"Kind","kind":"select","icon":"landmark"},{"key":"details","label":"Number","kind":"secret","mono":true,"icon":"credit-card"},{"key":"cvv","label":"CVV","kind":"secret","mono":true,"icon":"key-round"},{"key":"expiry","label":"Expires","kind":"text","mono":true,"icon":"calendar"}]},
  {"id":"license","label":"Software license","plural":"Licenses","icon":"award","titleKey":"product_name","primary":"serial_key","fields":[{"key":"product_name","label":"Product","kind":"text"},{"key":"serial_key","label":"Serial key","kind":"secret","mono":true,"icon":"key-round"},{"key":"activation_info","label":"Activation","kind":"text","icon":"info"},{"key":"expiration","label":"Expires","kind":"date","icon":"calendar"}]},
  {"id":"legal","label":"Legal contract","plural":"Legal","icon":"scale","titleKey":"name","primary":"summary","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"summary","label":"Summary","kind":"multiline","icon":"file-text"},{"key":"parties_involved","label":"Parties","kind":"text","icon":"users"},{"key":"signed_date","label":"Signed","kind":"date","icon":"calendar"}]},
  {"id":"document","label":"Document","plural":"Documents","icon":"file-lock-2","titleKey":"name","primary":"password","fields":[{"key":"name","label":"Name","kind":"text"},{"key":"file","label":"File","kind":"file"},{"key":"password","label":"Document password","kind":"password","icon":"key-round"},{"key":"tags","label":"Tags","kind":"tags","icon":"tag"},{"key":"expiry","label":"Expires","kind":"date","icon":"calendar"}]},
  {"id":"photo","label":"Photo","plural":"Photos","icon":"image","titleKey":"name","primary":null,"fields":[{"key":"name","label":"Name","kind":"text"},{"key":"file","label":"Image","kind":"file"}]},
  {"id":"audio","label":"Audio","plural":"Audio","icon":"music","titleKey":"name","primary":null,"fields":[{"key":"name","label":"Name","kind":"text"},{"key":"file","label":"Audio file","kind":"file"}]},
  {"id":"video","label":"Video","plural":"Video","icon":"video","titleKey":"name","primary":null,"fields":[{"key":"name","label":"Name","kind":"text"},{"key":"file","label":"Video file","kind":"file"}]}
];

const BY = Object.fromEntries(TYPES.map((t) => [t.id, t]));
export const getType = (id) => BY[id] || BY.note;
export const SECRET_KINDS = new Set(["password", "secret", "secretBlock", "totp", "codes", "note", "env"]);
export const typeIcon = (it) => (it.type === "password" ? undefined : getType(it.type).icon);
export const FILTERS = ["password", "totp", "apikey", "token", "ssh_key", "ssh_config", "cloud", "banking", "wifi", "govid", "note", "recovery", "certificate", "docker", "cicd", "k8s", "license", "legal", "medical", "travel", "contact", "document", "photo", "audio", "video"];
